package doc_test

import (
	"bytes"
	"context"
	"encoding/base64"
	"errors"
	"fmt"
	"image"
	"image/color"
	"image/png"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
	"unicode"
	"unicode/utf8"

	"github.com/scottdensmore/rcptpixie/internal/doc"
)

// fixture returns the path of a committed testdata file, skipping the test when
// it is absent so a checkout without regenerated fixtures still runs green.
func fixture(t *testing.T, name string) string {
	t.Helper()
	p := filepath.Join("testdata", name)
	if _, err := os.Stat(p); err != nil {
		t.Skipf("fixture %s missing; regenerate with: cd scripts/genfixtures && go run .", p)
	}
	return p
}

// page is one synthetic PDF page: text lines, or a filled rectangle when lines
// is empty (a page with no text layer at all).
type page struct {
	lines []string
	// broken declares the content stream as FlateDecode while storing plain
	// bytes, so extracting that one page fails.
	broken bool
}

// buildPDF writes a small hand-assembled PDF. It exists so the parser tests do
// not depend on fixtures generated by a separate module.
func buildPDF(t *testing.T, path string, pages []page) string {
	t.Helper()

	n := len(pages)
	kids := make([]string, 0, n)
	for i := range pages {
		kids = append(kids, fmt.Sprintf("%d 0 R", 3+2*i))
	}
	fontRef := 3 + 2*n

	objs := []string{
		"<< /Type /Catalog /Pages 2 0 R >>",
		fmt.Sprintf("<< /Type /Pages /Kids [%s] /Count %d >>", strings.Join(kids, " "), n),
	}
	for i := range pages {
		objs = append(objs, fmt.Sprintf(
			"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 %d 0 R >> >> /Contents %d 0 R >>",
			fontRef, 4+2*i))
		objs = append(objs, streamObj(pages[i]))
	}
	objs = append(objs, "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>")

	var buf bytes.Buffer
	buf.WriteString("%PDF-1.4\n")
	offsets := make([]int, len(objs))
	for i, body := range objs {
		offsets[i] = buf.Len()
		fmt.Fprintf(&buf, "%d 0 obj\n%s\nendobj\n", i+1, body)
	}
	xref := buf.Len()
	fmt.Fprintf(&buf, "xref\n0 %d\n", len(objs)+1)
	buf.WriteString("0000000000 65535 f \n")
	for _, off := range offsets {
		fmt.Fprintf(&buf, "%010d 00000 n \n", off)
	}
	fmt.Fprintf(&buf, "trailer\n<< /Size %d /Root 1 0 R >>\nstartxref\n%d\n%%%%EOF\n", len(objs)+1, xref)

	if err := os.WriteFile(path, buf.Bytes(), 0o644); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
	return path
}

func streamObj(pg page) string {
	if pg.broken {
		content := "BT\n/F1 12 Tf\n72 720 Td\n(DAMAGED PAGE) Tj\nET\n"
		return fmt.Sprintf("<< /Length %d /Filter /FlateDecode >>\nstream\n%s\nendstream", len(content), content)
	}
	var content string
	if len(pg.lines) == 0 {
		// Ink on the page, but nothing a text extractor can read.
		content = "0 0 0 rg\n100 100 400 500 re\nf\n"
	} else {
		var b strings.Builder
		b.WriteString("BT\n/F1 12 Tf\n72 720 Td\n14 TL\n")
		for i, line := range pg.lines {
			if i > 0 {
				b.WriteString("T*\n")
			}
			fmt.Fprintf(&b, "(%s) Tj\n", line)
		}
		b.WriteString("ET\n")
		content = b.String()
	}
	return fmt.Sprintf("<< /Length %d >>\nstream\n%s\nendstream", len(content), content)
}

func textPDF(t *testing.T, lines ...string) string {
	t.Helper()
	return buildPDF(t, filepath.Join(t.TempDir(), "receipt.pdf"), []page{{lines: lines}})
}

var receiptLines = []string{
	"Test Store",
	"123 Main Street",
	"Date: 2023-01-15",
	"1x Coffee            4.50",
	"1x Sandwich          9.95",
	"Subtotal           114.00",
	"Tax                  9.45",
	"TOTAL              123.45",
}

func TestExtractPDFTextSynthetic(t *testing.T) {
	path := textPDF(t, receiptLines...)
	text, pages, err := doc.ExtractPDFText(context.Background(), path, 3, nil)
	if err != nil {
		t.Fatalf("ExtractPDFText: %v", err)
	}
	if pages != 1 {
		t.Errorf("pages = %d, want 1", pages)
	}
	for _, want := range []string{"Test Store", "123.45", "2023-01-15"} {
		if !strings.Contains(text, want) {
			t.Errorf("text is missing %q:\n%s", want, text)
		}
	}
}

func TestExtractPDFTextFixture(t *testing.T) {
	path := fixture(t, "receipt-text.pdf")
	text, pages, err := doc.ExtractPDFText(context.Background(), path, 3, nil)
	if err != nil {
		t.Fatalf("ExtractPDFText: %v", err)
	}
	if pages <= 0 {
		t.Errorf("pages = %d, want > 0", pages)
	}
	for _, want := range []string{"Test Store", "123.45"} {
		if !strings.Contains(text, want) {
			t.Errorf("text is missing %q:\n%s", want, text)
		}
	}
}

func TestExtractPDFTextMultipage(t *testing.T) {
	path := buildPDF(t, filepath.Join(t.TempDir(), "multi.pdf"), []page{
		{lines: []string{"PAGE ONE MARKER"}},
		{lines: []string{"PAGE TWO MARKER"}},
		{lines: []string{"PAGE THREE MARKER"}},
	})

	text, pages, err := doc.ExtractPDFText(context.Background(), path, 3, nil)
	if err != nil {
		t.Fatalf("ExtractPDFText: %v", err)
	}
	if pages != 3 {
		t.Errorf("pages = %d, want 3", pages)
	}
	for _, want := range []string{"PAGE ONE MARKER", "PAGE TWO MARKER", "PAGE THREE MARKER"} {
		if !strings.Contains(text, want) {
			t.Errorf("text is missing %q:\n%s", want, text)
		}
	}

	// maxPages is a real bound, not advice.
	text, _, err = doc.ExtractPDFText(context.Background(), path, 1, nil)
	if err != nil {
		t.Fatalf("ExtractPDFText: %v", err)
	}
	if strings.Contains(text, "PAGE TWO MARKER") {
		t.Errorf("maxPages=1 read past page 1:\n%s", text)
	}
}

// TestExtractPDFTextSkipsBadPage guards the old behaviour of returning on the
// first page error, which discarded page 1 — where the total and date live.
func TestExtractPDFTextSkipsBadPage(t *testing.T) {
	path := buildPDF(t, filepath.Join(t.TempDir(), "damaged.pdf"), []page{
		{lines: []string{"GOOD PAGE ONE"}},
		{broken: true},
		{lines: []string{"GOOD PAGE THREE"}},
	})

	text, _, err := doc.ExtractPDFText(context.Background(), path, 3, nil)
	if err != nil {
		t.Fatalf("ExtractPDFText: %v", err)
	}
	for _, want := range []string{"GOOD PAGE ONE", "GOOD PAGE THREE"} {
		if !strings.Contains(text, want) {
			t.Errorf("text is missing %q:\n%s", want, text)
		}
	}
}

// TestExtractPDFTextClosesFile is the fd-leak regression: the old code never
// closed the file and died at ~1000 PDFs with "too many open files".
func TestExtractPDFTextClosesFile(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping fd-exhaustion loop in short mode")
	}
	path := textPDF(t, receiptLines...)
	for i := 0; i < 2000; i++ {
		if _, _, err := doc.ExtractPDFText(context.Background(), path, 1, nil); err != nil {
			t.Fatalf("iteration %d: %v", i, err)
		}
	}
}

// TestExtractPDFTextCorrupt is the guard against reintroducing the dslipak
// spin: a malformed PDF must return an error, never panic and never hang.
func TestExtractPDFTextCorrupt(t *testing.T) {
	dir := t.TempDir()
	good := buildPDF(t, filepath.Join(dir, "good.pdf"), []page{{lines: receiptLines}})
	raw, err := os.ReadFile(good)
	if err != nil {
		t.Fatal(err)
	}

	cases := map[string][]byte{
		"garbage":   []byte("%PDF-1.4\n" + strings.Repeat("\x00\xff\xfe not a pdf at all ", 200)),
		"truncated": raw[:len(raw)/2],
		"header":    []byte("this file is not a PDF at all\n"),
		"empty":     []byte("%PDF-1.4\n%%EOF\n"),
	}
	// Deterministic byte flips in the xref region.
	flipped := append([]byte(nil), raw...)
	for i, off := range []int{40, 55, 61, 70, 83, 97, 111, 130} {
		if p := len(flipped) - 1 - off; p > 8 {
			flipped[p] ^= byte(0x5a + i)
		}
	}
	cases["xref-flips"] = flipped

	for name, data := range cases {
		t.Run(name, func(t *testing.T) {
			path := filepath.Join(t.TempDir(), name+".pdf")
			if err := os.WriteFile(path, data, 0o644); err != nil {
				t.Fatal(err)
			}
			type result struct {
				text string
				err  error
			}
			done := make(chan result, 1)
			go func() {
				text, _, err := doc.ExtractPDFText(context.Background(), path, 3, nil)
				done <- result{text, err}
			}()
			select {
			case res := <-done:
				// A parser that returns no text and no error is acceptable: Load
				// sends that down the vision path. A hang or a panic is not.
				if res.err != nil && !errors.Is(res.err, doc.ErrPDFParse) {
					t.Fatalf("err = %v, want ErrPDFParse", res.err)
				}
				if res.err == nil && strings.TrimSpace(res.text) != "" {
					t.Fatalf("corrupt pdf yielded text: %q", res.text)
				}
			case <-time.After(10 * time.Second):
				t.Fatal("ExtractPDFText hung on a corrupt PDF")
			}
		})
	}
}

func TestExtractPDFTextEncrypted(t *testing.T) {
	path := fixture(t, "receipt-encrypted.pdf")
	_, _, err := doc.ExtractPDFText(context.Background(), path, 3, nil)
	if !errors.Is(err, doc.ErrEncrypted) {
		t.Fatalf("err = %v, want ErrEncrypted", err)
	}
}

func TestExtractPDFTextCancelled(t *testing.T) {
	path := textPDF(t, receiptLines...)
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	if _, _, err := doc.ExtractPDFText(ctx, path, 3, nil); err != nil && !errors.Is(err, context.Canceled) {
		t.Fatalf("err = %v, want nil or context.Canceled", err)
	}
}

func TestLoadTextPDFStaysText(t *testing.T) {
	path := textPDF(t, receiptLines...)
	d, err := doc.Load(context.Background(), path, nil, nil)
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if d.Kind != doc.KindText {
		t.Fatalf("Kind = %v, want KindText", d.Kind)
	}
	if len(d.Images) != 0 {
		t.Errorf("Images = %d, want 0", len(d.Images))
	}
	if !strings.Contains(d.Text, "123.45") {
		t.Errorf("text is missing the total:\n%s", d.Text)
	}
	if d.ModTime.IsZero() {
		t.Error("ModTime is zero")
	}
}

func scannedPDF(t *testing.T) string {
	t.Helper()
	return buildPDF(t, filepath.Join(t.TempDir(), "scanned.pdf"), []page{{}, {}})
}

func TestLoadScannedGoesToVision(t *testing.T) {
	path := scannedPDF(t)

	// With no rasterizer the user must be told what to install.
	_, err := doc.Load(context.Background(), path, nil, nil)
	if !errors.Is(err, doc.ErrNoRasterizer) {
		t.Fatalf("err = %v, want ErrNoRasterizer", err)
	}
	if !strings.Contains(err.Error(), "poppler") {
		t.Errorf("error does not name poppler: %v", err)
	}

	r := doc.Detect(nil)
	if r.Name() == "none" {
		t.Skip("no rasterizer on PATH")
	}
	d, err := doc.Load(context.Background(), path, r, nil)
	if err != nil {
		t.Fatalf("Load with %s: %v", r.Name(), err)
	}
	if d.Kind != doc.KindImages {
		t.Fatalf("Kind = %v, want KindImages", d.Kind)
	}
	if len(d.Images) == 0 || d.Pages != len(d.Images) {
		t.Fatalf("Images = %d, Pages = %d", len(d.Images), d.Pages)
	}
	for i, img := range d.Images {
		if strings.HasPrefix(img, "data:") {
			t.Fatalf("image %d carries a data: prefix", i)
		}
		raw, err := base64.StdEncoding.DecodeString(img)
		if err != nil {
			t.Fatalf("image %d is not bare base64: %v", i, err)
		}
		cfg, _, err := image.DecodeConfig(bytes.NewReader(raw))
		if err != nil {
			t.Fatalf("image %d does not decode: %v", i, err)
		}
		if cfg.Width <= 0 || cfg.Height <= 0 {
			t.Fatalf("image %d is %dx%d", i, cfg.Width, cfg.Height)
		}
	}
}

// TestLoadScannedFixtureReallyHasNoTextLayer keeps the vision path honest: a
// regenerated fixture that gained a text layer would leave it untested while
// every other test still passed.
func TestLoadScannedFixtureReallyHasNoTextLayer(t *testing.T) {
	assertNoTextLayer := func(t *testing.T, path string) {
		t.Helper()
		text, _, err := doc.ExtractPDFText(context.Background(), path, 3, nil)
		if err != nil {
			t.Fatalf("%s: %v", path, err)
		}
		n := 0
		for _, r := range text {
			if !unicode.IsSpace(r) {
				n++
			}
		}
		if n >= doc.MinTextChars {
			t.Errorf("%s has %d text runes, at or over MinTextChars %d: the vision path is no longer exercised",
				path, n, doc.MinTextChars)
		}
	}
	t.Run("synthetic", func(t *testing.T) { assertNoTextLayer(t, scannedPDF(t)) })
	t.Run("fixture", func(t *testing.T) { assertNoTextLayer(t, fixture(t, "receipt-scanned.pdf")) })
}

func writePNG(t *testing.T, path string, w, h int) string {
	t.Helper()
	img := image.NewRGBA(image.Rect(0, 0, w, h))
	for y := 0; y < h; y++ {
		for x := 0; x < w; x++ {
			img.Set(x, y, color.RGBA{R: uint8(x), G: uint8(y), B: 0x40, A: 0xff})
		}
	}
	f, err := os.Create(path)
	if err != nil {
		t.Fatal(err)
	}
	defer f.Close()
	if err := png.Encode(f, img); err != nil {
		t.Fatal(err)
	}
	return path
}

func TestLoadImageIsBareBase64(t *testing.T) {
	paths := []string{writePNG(t, filepath.Join(t.TempDir(), "receipt.png"), 64, 48)}
	if _, err := os.Stat(filepath.Join("testdata", "receipt.jpg")); err == nil {
		paths = append(paths, filepath.Join("testdata", "receipt.jpg"))
	}

	for _, path := range paths {
		d, err := doc.Load(context.Background(), path, nil, nil)
		if err != nil {
			t.Fatalf("Load %s: %v", path, err)
		}
		if d.Kind != doc.KindImages {
			t.Errorf("%s Kind = %v, want KindImages", path, d.Kind)
		}
		if len(d.Images) != 1 || d.Pages != 1 {
			t.Fatalf("%s Images = %d, Pages = %d, want 1 and 1", path, len(d.Images), d.Pages)
		}
		if strings.HasPrefix(d.Images[0], "data:") {
			t.Errorf("%s carries a data: prefix", path)
		}
		raw, err := base64.StdEncoding.DecodeString(d.Images[0])
		if err != nil {
			t.Fatalf("%s is not bare base64: %v", path, err)
		}
		want, err := os.ReadFile(path)
		if err != nil {
			t.Fatal(err)
		}
		if !bytes.Equal(raw, want) {
			t.Errorf("%s: decoded bytes differ from the file", path)
		}
	}
}

func TestLoadRejectsOversizeImage(t *testing.T) {
	path := filepath.Join(t.TempDir(), "huge.png")
	f, err := os.Create(path)
	if err != nil {
		t.Fatal(err)
	}
	if err := f.Truncate(doc.MaxImageBytes + 1); err != nil {
		t.Fatal(err)
	}
	f.Close()

	_, err = doc.Load(context.Background(), path, nil, nil)
	if err == nil {
		t.Fatal("Load accepted an oversize image")
	}
	if !strings.Contains(err.Error(), fmt.Sprint(doc.MaxImageBytes)) {
		t.Errorf("error does not report the limit: %v", err)
	}
}

func TestLoadUnsupported(t *testing.T) {
	path := filepath.Join(t.TempDir(), "notes.docx")
	if err := os.WriteFile(path, []byte("x"), 0o644); err != nil {
		t.Fatal(err)
	}
	if _, err := doc.Load(context.Background(), path, nil, nil); !errors.Is(err, doc.ErrUnsupported) {
		t.Fatalf("err = %v, want ErrUnsupported", err)
	}
}

const omissionSignature = " characters omitted ...]"

func TestTruncate(t *testing.T) {
	sizes := []int{0, 1, 63, 100, 101, 999, 1000, 5000, 12000, 12001, 50000}
	limits := []int{100, 1000, 12000}

	for _, size := range sizes {
		s := syntheticText(size)
		for _, limit := range limits {
			out, truncated := doc.Truncate(s, limit)
			if len(out) > limit {
				t.Errorf("size %d limit %d: len(out) = %d, over the limit", size, limit, len(out))
			}
			if !utf8.ValidString(out) {
				t.Errorf("size %d limit %d: output is not valid UTF-8", size, limit)
			}
			if truncated != (len(s) > limit) {
				t.Errorf("size %d limit %d: truncated = %v", size, limit, truncated)
			}
			if !truncated {
				if out != s {
					t.Errorf("size %d limit %d: untruncated output differs from the input", size, limit)
				}
				continue
			}
			if n := strings.Count(out, omissionSignature); n != 1 {
				t.Fatalf("size %d limit %d: omission marker appears %d times", size, limit, n)
			}
			_, tail, _ := strings.Cut(out, omissionSignature)
			tail = strings.TrimPrefix(tail, "\n")
			if tail == "" || !strings.HasSuffix(s, tail) {
				t.Fatalf("size %d limit %d: the tail of the input did not survive (kept %d bytes)", size, limit, len(tail))
			}
			// The TOTAL lives in the last lines; losing it defeats the tool.
			if limit >= 1000 && len(tail) < 200 {
				t.Errorf("size %d limit %d: only %d trailing bytes kept, want >= 200", size, limit, len(tail))
			}
		}
	}
}

func TestTruncateInvalidUTF8(t *testing.T) {
	s := strings.Repeat("caf\xc3", 4000) // truncated é bytes throughout
	out, _ := doc.Truncate(s, 1000)
	if !utf8.ValidString(out) {
		t.Fatal("output is not valid UTF-8")
	}
	if len(out) > 1000 {
		t.Fatalf("len(out) = %d, over the limit", len(out))
	}
}

// syntheticText builds n bytes of receipt-shaped, valid UTF-8 text ending in a
// recognisable total line.
func syntheticText(n int) string {
	if n == 0 {
		return ""
	}
	var b strings.Builder
	line := 0
	for b.Len() < n {
		fmt.Fprintf(&b, "%04d Café Ünïcode item — 12.34\n", line)
		line++
	}
	s := b.String()[:n]
	// Keep the result valid UTF-8 after the hard cut.
	for len(s) > 0 && !utf8.ValidString(s) {
		s = s[:len(s)-1]
	}
	return s
}
