name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: go mod download

      - name: Install Ollama
        run: |
          curl -fsSL https://ollama.com/install.sh | sh
          ollama pull llama2
          # Start Ollama in the background
          ollama serve &
      
      - name: Wait for Ollama to start
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:11434/api/tags > /dev/null; then
              echo "Ollama is ready!"
              break
            fi
            if [ $i -eq 30 ]; then
              echo "Ollama failed to start within 30 seconds"
              journalctl -u ollama.service # Log output for debugging
              exit 1
            fi
            echo "Waiting for Ollama to start... ($i/30)"
            sleep 1
          done

      - name: Run tests
        run: go test -v ./...
        env:
          SKIP_INTEGRATION_TESTS: "false"